### ISSUE TITLE
Communication Inclusivity: Alternatives Question

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#163]
Again, this question is not clear

**Comment by emmairwin** [comment]
Can you say more about this issue?

**Comment by germonprez** [comment]
Sorry @emmairwin -- Just saying that a question is needed. I just put notes on here as I was aligning with the metrics repository

**Comment by geekygirldawn** [comment]
This is a duplicate of #109. The question isn't clear because we haven't developed a question or the resource page for the [Communication Inclusivity: Alternatives](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/communication/communication-inclusivity-alternatives.md) metric :)
