### ISSUE TITLE
Candidate Release Comments (Mentorship)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-diversity-inclusion#186]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Mentorship**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/leadership/mentorship.md

Release candidate: https://chaoss.community/metric-mentorship/

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by foundjem** [comment]
Interesting!

Moreover, Mentorship if conducted properly could help educate mentees about the work culture of a project/community. Also, well-formed mentees can contribute quality code, which represent best practices because they have learned these skills over the Mentorship period. 

- Have some few questions though, how long will the mentorship program last? 
- Can a mentee change their mentor after the mentorship have started?
- Can a mentee be allowed to participate in more than  one mentorship program in a row?

**Comment by germonprez** [comment]
Same Likert scale comment as in the other metrics. Make them all 1-5 to allow for neutral option.

**Comment by GeorgLink** [comment]
I see @foundjem's comment as very practical implementation questions. We should discuss how this translates to questions to understand the D&I of our projects.

**Comment by dicortazar** [comment]
Moving @foundjem comments to #201
