### ISSUE TITLE
Release Candidate Comments (Issue Label Inclusivity)

### ISSUE THREAD

**Issue by mariamgui** [chaoss/wg-diversity-inclusion#291]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Issue Label Inclusivity**

GitHub location: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/README.md

See all release candidates of metrics are at:
[https://chaoss.community/metrics-202008/](https://chaoss.community/metrics-202008/)

**Comment by klumb** [comment]
link to the metric:
https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/project-and-community/issue-label-inclusivity.md

**Comment by foundjem** [comment]
This metric seems too broad, is it capturing how a particular project is inclusive?

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by germonprez** [comment]
It is working to capture if the labels associated with issues can be used to improve inclusiveness of a project.

**Comment by mbbroberg** [comment]
I find this metric to be straightforward and unique overall, but I do have a couple thoughts for it. 

### 1 - are the listed filter correct for this metric? 

Based on the title and objective to (paraphrasing) capture data about the clarity of and usability of labels, the filters don't line up since they are general metrics on issues themselves as opposed to scoping to the objective. Some filters that come to mind as I read (with explanations why):  

- Number of labels (because there's a sweet spot between too few and too many that needs to be measured) 
- Number of labels for same type of issue (with the implication that having `bug`, `Bugs, and `area/bugs` being difficult for contributors and especially newcomers to understand) 
- Inactive labels (e.g. labels not in use or never in use. This could be part of regular maintenance to delete unhelpful labels)

### 2 - does it make sense to have dependencies across metrics? 

The following line under Objective mentions another metric as an input for this metric: 

> Usable Title and Description: Issue titles and descriptions follow the Documentation Usability metric objectives

At first glance, I'm not sure what the `Documentation Usability metric` is, so a link would be helpful. Secondly, I think these would better serve users if the metrics as independent of each other.

**Comment by mariamgui** [comment]
The idea of this metric is to gauge whether or not the issue list and more precisely its labels speaks to a variety of contributors that have different goals (code, documentation, translation, etc...) and are at different contribution stages (newcomer, expert etc...). An ideal scenario would be for anyone to be able to find an issue to work on and for the labels to be defined in a way that makes the choosing process as straightforward as possible. 

- The idea of being able to detect repetitive labels that are spelled/ formulated differently is really interesting from a usability perspective in general. It should be possible to detect that in the list of labels predefined by a project. This could fit under the **_consistent use of labels_** objective. 
- For the number of labels filter it might be tricky to define a threshold that can apply to all projects since they will differ in size, complexity.. 
- Inactive labels are interesting from a usability perspective too, I am wondering how can we define an inactive label (maybe one that hasn't been used in three months or a year). My understanding is this would still involve defining a threshold that might not be universal for all projects. I wonder if there is a threshold or some best practices in literature that covers that.

The dependencies across metrics is a really good point. From a user perspective it would be easier to have the metrics be independent but from a design perspective it would be repetitive to have metrics be independent. I am wondering whether there was a case where two or more metrics are dependent from one another and how was that handled.
__
The idea behind the issue title and description to follow the _Documentation Usability metric_ is to avoid _**technical jargon**_ and _**_focus on readability_**_, _**_structural clarity_**_ and **language inclusion.**

**Comment by mbbroberg** [comment]
Great points and I appreciate the thoughtful response! 

>  The idea behind the issue title and description to follow the Documentation Usability metric is to avoid technical jargon and focus on readability, structural clarity and language inclusion.

I am in full support of capturing all of the above. As a user of this metric, I'm not sure what I am expected to come with vs what I learn from this metric in the process of using it. For instance

- with 'technical jargon' -- do I bring a set of terms that are technical jargon and implement this metric by counting the usage of them across the project? 
- for 'readability' -- do I bring my own standard of readability to this metric or is there a standard on readability we are referring users to? I see the objective listed, and the part I feel confident I could measure is sentence length (though it's not clear how short is readable v. unreadable). 

This metric is full of expert advice around documentation, but I'm finding it difficult to understand as a user both (a) independent of [Documentation Usability](https://github.com/chaoss/wg-diversity-inclusion/blob/72c2d2c84b427ed58ac87047f4d4371c4dea47e0/focus-areas/project-and-community/documentation-usability.md) and (b) reviewing both together. 

Some suggestions that come to mind (with my naive understanding -- apologies, I haven't been part of the WG, but hopefully those fresh eyes can be helpful): 

* Separate the aggregate/synthetic metric from its atomic metric parts. Each of the objectives are complex and nuanced enough to be there own atomic, while Label Incivility reads as an synthetic. 
* For the atomic metrics, consider each metric being a collection of specific metrics that are either boolean or provide a spectrum toward self assessment.
  * Ex: "This project is newcomer-friendly bc it has X labels as well as core-contributor friendly because it follows a consistent namespacing pattern (`area/type` or `area:type`)

**Comment by germonprez** [comment]
@mbbroberg could you take a shot at issuing a PR based on these suggested changes?

**Comment by klumb** [comment]
@mariamgui, is this metric ready?

**Comment by germonprez** [comment]
Ready for release

**Comment by mariamgui** [comment]
@klumb I believe it's ready :)

**Comment by klumb** [comment]
Thanks @mariamgui and @germonprez
